coorrency.settings:
  type: config_object
  label: 'Coorrency settings'
  mapping:
    coorrency:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Coorrency converter page title:'
        ajax:
          type: integer
          label: 'Ajax call on API:'
block.settings.coorrency_block:
  type: block_settings
  label: 'Coorrency block'
  mapping:
    coorrency_block_settings:
